export const GRID_SIZE = 26;
export const TILE_SIZE = 16;
export const CANVAS_WIDTH = GRID_SIZE * TILE_SIZE;
export const CANVAS_HEIGHT = GRID_SIZE * TILE_SIZE;

export const TANK_SIZE = 32;
export const TANK_SPEED = 2;
export const BULLET_SIZE = 8;
export const BULLET_SPEED = 4;

export const SHOOT_COOLDOWN = 30;
export const RAPID_FIRE_COOLDOWN = 15;
export const SPAWN_INTERVAL = 180;
export const MAX_ENEMIES_ON_SCREEN = 4;
export const ENEMY_THINK_INTERVAL = 60;

export const PLAYER_START_LIVES = 3;
export const SPAWN_INVINCIBILITY_FRAMES = 60;
export const SHIELD_DURATION = 300;
export const RAPID_FIRE_DURATION = 600;
export const POWERUP_LIFETIME = 600;
export const EXPLOSION_FRAMES = 20;

export const COLORS = {
  EMPTY: '#000000',
  BRICK: '#8B4513',
  STEEL: '#808080',
  WATER: '#4169E1',
  GRASS: '#228B22',
  BASE: '#FFD700',
  PLAYER_TANK: '#00FF00',
  PLAYER2_TANK: '#00FFFF',
  ENEMY_BASIC: '#FF0000',
  ENEMY_FAST: '#FFA500',
  ENEMY_ARMORED: '#FFB6C1',
  BULLET: '#FFFF00',
  EXPLOSION: ['#FF0000', '#FF8800', '#FFFF00', '#FFFFFF'],
  SHIELD: '#00FFFF',
  POWERUP_SHIELD: '#00FFFF',
  POWERUP_RAPIDFIRE: '#FF00FF',
  POWERUP_LIFE: '#00FF00',
};
