import { Level } from '../types/game';

export const LEVELS: Level[] = [
  {
    id: 'hengdao-lima',
    name: '横刀立马',
    parSteps: 81,
    blocks: [
      { id: 'caocao', type: 'caocao', size: { width: 2, height: 2 }, position: { row: 0, col: 1 }, label: '曹操' },
      { id: 'guanyu', type: 'guanyu', size: { width: 2, height: 1 }, position: { row: 2, col: 1 }, label: '关羽' },
      { id: 'zhangfei', type: 'vertical', size: { width: 1, height: 2 }, position: { row: 0, col: 0 }, label: '张飞' },
      { id: 'zhaoyun', type: 'vertical', size: { width: 1, height: 2 }, position: { row: 0, col: 3 }, label: '赵云' },
      { id: 'machao', type: 'vertical', size: { width: 1, height: 2 }, position: { row: 2, col: 0 }, label: '马超' },
      { id: 'huangzhong', type: 'vertical', size: { width: 1, height: 2 }, position: { row: 2, col: 3 }, label: '黄忠' },
      { id: 'soldier1', type: 'soldier', size: { width: 1, height: 1 }, position: { row: 3, col: 1 }, label: '兵' },
      { id: 'soldier2', type: 'soldier', size: { width: 1, height: 1 }, position: { row: 3, col: 2 }, label: '兵' },
      { id: 'soldier3', type: 'soldier', size: { width: 1, height: 1 }, position: { row: 4, col: 0 }, label: '兵' },
      { id: 'soldier4', type: 'soldier', size: { width: 1, height: 1 }, position: { row: 4, col: 3 }, label: '兵' },
    ],
  },
  {
    id: 'zhizhi-ruoding',
    name: '指挥若定',
    parSteps: 70,
    blocks: [
      { id: 'caocao', type: 'caocao', size: { width: 2, height: 2 }, position: { row: 0, col: 1 }, label: '曹操' },
      { id: 'guanyu', type: 'guanyu', size: { width: 2, height: 1 }, position: { row: 2, col: 1 }, label: '关羽' },
      { id: 'zhangfei', type: 'vertical', size: { width: 1, height: 2 }, position: { row: 0, col: 0 }, label: '张飞' },
      { id: 'zhaoyun', type: 'vertical', size: { width: 1, height: 2 }, position: { row: 0, col: 3 }, label: '赵云' },
      { id: 'machao', type: 'vertical', size: { width: 1, height: 2 }, position: { row: 2, col: 0 }, label: '马超' },
      { id: 'huangzhong', type: 'vertical', size: { width: 1, height: 2 }, position: { row: 2, col: 3 }, label: '黄忠' },
      { id: 'soldier1', type: 'soldier', size: { width: 1, height: 1 }, position: { row: 3, col: 0 }, label: '兵' },
      { id: 'soldier2', type: 'soldier', size: { width: 1, height: 1 }, position: { row: 3, col: 1 }, label: '兵' },
      { id: 'soldier3', type: 'soldier', size: { width: 1, height: 1 }, position: { row: 3, col: 2 }, label: '兵' },
      { id: 'soldier4', type: 'soldier', size: { width: 1, height: 1 }, position: { row: 3, col: 3 }, label: '兵' },
    ],
  },
  {
    id: 'binglin-chengxia',
    name: '兵临城下',
    parSteps: 100,
    blocks: [
      { id: 'caocao', type: 'caocao', size: { width: 2, height: 2 }, position: { row: 0, col: 1 }, label: '曹操' },
      { id: 'guanyu', type: 'guanyu', size: { width: 2, height: 1 }, position: { row: 2, col: 1 }, label: '关羽' },
      { id: 'zhangfei', type: 'vertical', size: { width: 1, height: 2 }, position: { row: 0, col: 0 }, label: '张飞' },
      { id: 'zhaoyun', type: 'vertical', size: { width: 1, height: 2 }, position: { row: 2, col: 0 }, label: '赵云' },
      { id: 'machao', type: 'vertical', size: { width: 1, height: 2 }, position: { row: 2, col: 3 }, label: '马超' },
      { id: 'huangzhong', type: 'vertical', size: { width: 1, height: 2 }, position: { row: 0, col: 3 }, label: '黄忠' },
      { id: 'soldier1', type: 'soldier', size: { width: 1, height: 1 }, position: { row: 3, col: 0 }, label: '兵' },
      { id: 'soldier2', type: 'soldier', size: { width: 1, height: 1 }, position: { row: 3, col: 1 }, label: '兵' },
      { id: 'soldier3', type: 'soldier', size: { width: 1, height: 1 }, position: { row: 3, col: 2 }, label: '兵' },
      { id: 'soldier4', type: 'soldier', size: { width: 1, height: 1 }, position: { row: 3, col: 3 }, label: '兵' },
    ],
  },
  {
    id: 'cengceng-shefang',
    name: '层层设防',
    parSteps: 90,
    blocks: [
      { id: 'caocao', type: 'caocao', size: { width: 2, height: 2 }, position: { row: 0, col: 1 }, label: '曹操' },
      { id: 'guanyu', type: 'guanyu', size: { width: 2, height: 1 }, position: { row: 2, col: 1 }, label: '关羽' },
      { id: 'zhangfei', type: 'vertical', size: { width: 1, height: 2 }, position: { row: 0, col: 0 }, label: '张飞' },
      { id: 'zhaoyun', type: 'vertical', size: { width: 1, height: 2 }, position: { row: 0, col: 3 }, label: '赵云' },
      { id: 'machao', type: 'vertical', size: { width: 1, height: 2 }, position: { row: 2, col: 0 }, label: '马超' },
      { id: 'huangzhong', type: 'vertical', size: { width: 1, height: 2 }, position: { row: 2, col: 3 }, label: '黄忠' },
      { id: 'soldier1', type: 'soldier', size: { width: 1, height: 1 }, position: { row: 3, col: 1 }, label: '兵' },
      { id: 'soldier2', type: 'soldier', size: { width: 1, height: 1 }, position: { row: 4, col: 1 }, label: '兵' },
      { id: 'soldier3', type: 'soldier', size: { width: 1, height: 1 }, position: { row: 3, col: 2 }, label: '兵' },
      { id: 'soldier4', type: 'soldier', size: { width: 1, height: 1 }, position: { row: 4, col: 2 }, label: '兵' },
    ],
  },
  {
    id: 'simian-chuge',
    name: '四面楚歌',
    parSteps: 112,
    blocks: [
      { id: 'caocao', type: 'caocao', size: { width: 2, height: 2 }, position: { row: 0, col: 1 }, label: '曹操' },
      { id: 'guanyu', type: 'guanyu', size: { width: 2, height: 1 }, position: { row: 2, col: 0 }, label: '关羽' },
      { id: 'zhangfei', type: 'vertical', size: { width: 1, height: 2 }, position: { row: 0, col: 0 }, label: '张飞' },
      { id: 'zhaoyun', type: 'vertical', size: { width: 1, height: 2 }, position: { row: 0, col: 3 }, label: '赵云' },
      { id: 'machao', type: 'vertical', size: { width: 1, height: 2 }, position: { row: 2, col: 2 }, label: '马超' },
      { id: 'huangzhong', type: 'vertical', size: { width: 1, height: 2 }, position: { row: 2, col: 3 }, label: '黄忠' },
      { id: 'soldier1', type: 'soldier', size: { width: 1, height: 1 }, position: { row: 3, col: 0 }, label: '兵' },
      { id: 'soldier2', type: 'soldier', size: { width: 1, height: 1 }, position: { row: 3, col: 1 }, label: '兵' },
      { id: 'soldier3', type: 'soldier', size: { width: 1, height: 1 }, position: { row: 4, col: 0 }, label: '兵' },
      { id: 'soldier4', type: 'soldier', size: { width: 1, height: 1 }, position: { row: 4, col: 1 }, label: '兵' },
    ],
  },
];
