// 游戏配置常量
export const Config = {
  // Canvas
  CANVAS_BG_COLOR: '#1a1a2e',
  
  // 玩家配置
  PLAYER_RADIUS: 20,
  PLAYER_COLOR: '#FF6B6B',
  PLAYER_CHARGE_COLOR: '#FFD93D',
  
  // 物理配置
  GRAVITY: 2000,
  MIN_JUMP_FORCE: 400,
  MAX_JUMP_FORCE: 1200,
  MIN_CHARGE_TIME: 0.1,
  MAX_CHARGE_TIME: 2.0,
  JUMP_ANGLE: Math.PI / 4, // 45度
  
  // 平台配置
  PLATFORM_HEIGHT: 20,
  PLATFORM_MIN_WIDTH: 60,
  PLATFORM_MAX_WIDTH: 120,
  PLATFORM_MIN_DISTANCE: 120,
  PLATFORM_MAX_DISTANCE: 280,
  PLATFORM_VERTICAL_VARIATION: 80,
  INITIAL_PLATFORM_COUNT: 4,
  PLATFORM_COLORS: ['#4ECDC4', '#45B7D1', '#96CEB4', '#FFEAA7', '#DDA0DD'],
  
  // 难度配置
  DIFFICULTY_INCREASE_INTERVAL: 5,
  MAX_DIFFICULTY: 10,
  
  // 摄像机配置
  CAMERA_SMOOTH_FACTOR: 0.1,
  CAMERA_OFFSET_X_RATIO: 0.33,
  
  // 分数配置
  SCORE_NORMAL: 1,
  SCORE_PERFECT: 3,
  PERFECT_ZONE_RATIO: 0.2
};
